epochs: 100
steps_per_epoch: 1000
train_batch_size: 1024
env_name: D4RL/pointmaze/umaze-v2
scheduler: DDPM
tag: GN
seed: 0
eval_batch: 256
max_n_episodes: 10000
ckpt_path: ./ckpt/pointmaze/umaze
num_train_steps: 1000
beta_schedule: squaredcos_cap_v2
lr: 1e-3
clip_sample: false
loss_factor: 0.1
horizon: 64
action_weight: 10.0
predict_epsilon: true